1. Intro:
  - Homework 1 will be released next Tuesday
2. Lec 3: Numpy
  - Vectorization
  - Boardcast
  - Identify Matrix
  - Indexing and Slicing
  - Fancy Array
  - Reduction Operation

# Basic Section (Start)


In [1]:
import numpy as np

## Numpy (Review)

Main object type is `np.array`

Many ways to create it,

One way is to convert a python list

In [2]:
python_list = [ 1,2,3 ]
arr = np.array(python_list)
arr

array([1, 2, 3])

In [3]:
arr**2

array([1, 4, 9])

In [4]:
python_list**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
# class.function(self, args) = instance.function(args)

In [6]:
# Magic Function with __XXX__
arr.__pow__(2)
#python_list.__pow__(2)

array([1, 4, 9])

Many times a list comprehension is used to create a list and then converted to a array

In [8]:
python_list_pow = [ i**2 for i in python_list if i != 1] #list comprehension
python_list_pow
np.array(python_list_pow)

array([4, 9])

### Exercise (In Lec)
Create a numpy array that contain  intergers i  such that  0<i<100 and $2^i$ has the last digit 6

In [11]:
# YOUR CODE HERE
l = [i for i in range(1,100) if 2**i % 10 ==6]
l = np.array(l)
print(l)

[ 4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92 96]


Create a 2D numpy array $A$ (5,10) such that $A_{ij} = i\times j$

In [12]:
# YOUR CODE HERE
A = np.zeros((5,10))
for i in range(5):
  for j in range(10):
    A[i,j] = i*j

A

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36.]])

In [13]:
l = [[i*j for j in range(10)] for i in range(5)]
A = np.array(l)

A

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36]])

## Another way to create a numpy array is with initializing functions

- np.zeros
- np.ones
- np.arange

These functions along with `reshape` can be used to create initial matrix without any for loops

In [14]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones((10,10))*2

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [16]:
np.arange(2, 10, 2) #equivalent to range(2,10,2)

array([2, 4, 6, 8])

### Exercise (In Lec)

Create an array of first 10 powers of 2

In [17]:
# YOUR CODE HERE
l = 2**np.arange(10)
l

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

### 1D vs 2D array

In [18]:
array1D = np.arange(10)*np.arange(10)
print(array1D.shape)
array1D

(10,)


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [19]:
array2D = np.arange(10).reshape(10,1)
print(array2D.shape)
array2D

(10, 1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [20]:
array2D * array1D

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   1,   4,   9,  16,  25,  36,  49,  64,  81],
       [  0,   2,   8,  18,  32,  50,  72,  98, 128, 162],
       [  0,   3,  12,  27,  48,  75, 108, 147, 192, 243],
       [  0,   4,  16,  36,  64, 100, 144, 196, 256, 324],
       [  0,   5,  20,  45,  80, 125, 180, 245, 320, 405],
       [  0,   6,  24,  54,  96, 150, 216, 294, 384, 486],
       [  0,   7,  28,  63, 112, 175, 252, 343, 448, 567],
       [  0,   8,  32,  72, 128, 200, 288, 392, 512, 648],
       [  0,   9,  36,  81, 144, 225, 324, 441, 576, 729]])

### Distinction between numpy 1D arrays and numpy 2D arrays

This tends to cause a lot of confusion for new numpy users.
Follow the below examples carefully to understand the distinction.

In [21]:
Z = np.zeros(10)
print(Z)
Z.shape

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


(10,)

In [22]:
# Create 2D array by dimension
Z = np.zeros((10,1))
print(Z)
Z.shape

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


(10, 1)

In [23]:
# Create 2D array by reshape
Z = np.zeros(10).reshape(10,1)
print(Z)
Z.shape

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


(10, 1)

In [24]:
Z.squeeze() #remove axis with length = 1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
# squeeze Remove axes of length one
Z = np.zeros(6).reshape(1, 1, 2,3)
print(Z)
print(Z.shape, '\n')

Z_squeeze = Z.squeeze()
print(Z_squeeze)
print(Z_squeeze.shape)


[[[[0. 0. 0.]
   [0. 0. 0.]]]]
(1, 1, 2, 3) 

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [26]:
# Matrix Multiplication
Mat = np.random.randn(10,10)
Mat.shape

(10, 10)

In [27]:
Z = np.arange(10).reshape(10,1)
print(Z)
print(Z.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


In [28]:
# (N, M) @ (M, K) = (N, K)
Mat@Z

array([[  6.18415753],
       [  1.37214189],
       [ 32.61422904],
       [-23.24152584],
       [  4.39040664],
       [ -5.08435184],
       [-31.99421188],
       [-17.48648322],
       [ -4.25403633],
       [ 40.2884744 ]])

In [29]:
Z = np.arange(10).reshape(1,10)

print(Mat.shape)
print(Z.shape)

# (N, M) @ (M, K) = (N, K)
Mat@Z # (10, 10) @ (1, 10) NOT WORKING


(10, 10)
(1, 10)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 10)

In [30]:
(Z@Mat).shape

(1, 10)

In [32]:
# array variable is also a pointer
x = np.zeros((5,5))
print(x[1,1])
y = x.copy()
x[1,1]= 2

y

0.0


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Array Broadcasting

Normally you only do arithmetic operations between arrays of the same dimension

The smaller array of at least 1 dimension of size 1 is “broadcast” across the larger array so that they have compatible shapes by dimension.

In [33]:
a = np.arange(3)
b = np.arange(3).reshape(3,1)
c = np.ones((3,3))
d = np.zeros((6,3))
print(a, '\n')
print(b,'\n')
print(c,'\n')
print(d,'\n')

[0 1 2] 

[[0]
 [1]
 [2]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 



In [37]:
# c + 2
# c + c
# d + a
c + d

ValueError: operands could not be broadcast together with shapes (3,3) (6,3) 

In [38]:
np.ones((6,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [39]:
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

In [40]:
np.ones((6,1)) + np.ones((1,5))

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [41]:
X = np.arange(4).reshape(-1,1)*10
Y = np.arange(3).reshape(1,-1)
print(X.shape)
print(Y.shape,'\n')
print(X,'\n')
print(Y,'\n')
X+Y

(4, 1)
(1, 3) 

[[ 0]
 [10]
 [20]
 [30]] 

[[0 1 2]] 



array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [43]:
A = np.zeros((5,3,2))
A.reshape(-1,1).shape


(30, 1)

it tries to duplicates every x’s col and y’s row (dim size = 1) to match the other arrays
1. Make the two arrays have the same number of dimensions.
  - If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.

2. If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

![](http://scipy-lectures.org/_images/numpy_broadcasting.png)

### Exercise (In-Lecture)
create a 2D numpy array $A$ (shape = (5,10) ) such that $A_{ij} = i\times j$, but without using list comprehensions. Use broadcasting instead


In [ ]:
# hint: check how it looks for
#       np.arange(5).reshape(-1,1)
#       np.arange(10).reshape(1,-1)

In [46]:
# YOUR CODE HERE
A = np.arange(5).reshape(-1, 1) * np.arange(10).reshape(1,-1)
A

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36]])

Use array broadcasting to create a (10,10) numpy array with values
$$ A_{ij} = 2^i + j $$

In [ ]:
# Hint: Check the values of
#       2**(np.arange(10).reshape(-1,1))
#       np.arange(10).reshape(1,-1)

In [48]:
# YOUR CODE HERE
A = 2**(np.arange(10).reshape(-1, 1)) + np.arange(10).reshape(1, -1)
A

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [  4,   5,   6,   7,   8,   9,  10,  11,  12,  13],
       [  8,   9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 32,  33,  34,  35,  36,  37,  38,  39,  40,  41],
       [ 64,  65,  66,  67,  68,  69,  70,  71,  72,  73],
       [128, 129, 130, 131, 132, 133, 134, 135, 136, 137],
       [256, 257, 258, 259, 260, 261, 262, 263, 264, 265],
       [512, 513, 514, 515, 516, 517, 518, 519, 520, 521]])

# Basic Section (End)

## Matrix creation

There are some functions to create standard matrices

In [49]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
# np.diag: Extract a diagonal or construct a diagonal array.
M = np.diag(np.arange(10))#.reshape(5,20)
M

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [52]:
np.diag(M)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
# Transpose of the matrix
A = np.arange(15).reshape(5,3)
print(A.shape)
A

(5, 3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [54]:
A.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [55]:
A.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

### random seed

In [56]:
np.random.rand(5,5)

array([[0.27071453, 0.7787426 , 0.26977103, 0.14339811, 0.75946983],
       [0.31504401, 0.45623695, 0.47256913, 0.10542571, 0.00684927],
       [0.3150413 , 0.4170825 , 0.39331545, 0.59578278, 0.11265685],
       [0.41139584, 0.29191492, 0.42523396, 0.25837608, 0.47141152],
       [0.34202741, 0.56350169, 0.29173968, 0.15248661, 0.01425795]])

In [59]:
np.random.seed(0) #control the random state
np.random.rand(5,5)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443]])

### Exercise (Post Lecture)

Create this matrix   

```python
array([[5., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 4., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 4., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 5.]])
```

In [ ]:
# YOUR CODE HERE

## Array Indexing and Slicing

In [60]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr[5]

5

In [65]:
arr[-3]

7

In [66]:
arr[3:7]

array([3, 4, 5, 6])

In [67]:
arr[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr[0:-3]

array([0, 1, 2, 3, 4, 5, 6])

In [69]:
arr[0:6:2] #similar as range(0,6,2)

array([0, 2, 4])

In [70]:
arr[5:0:-2]

array([5, 3, 1])

In [71]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [72]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
a = 10*np.arange(6).reshape(-1,1)+np.arange(6)
print(a)
a[4:, 4:]

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


array([[44, 45],
       [54, 55]])

Can use all the above slicing methods for each dimension of a multidemnsional array
![](http://scipy-lectures.org/_images/numpy_indexing.png)

try it yourself

In [ ]:
for x in [0,4,6]:
  a[2::2, ::x] = x


In [76]:
a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [77]:
a[2::2,::2] = 100000
a

array([[     0,      1,      2,      3,      4,      5],
       [    10,     11,     12,     13,     14,     15],
       [100000,     21, 100000,     23, 100000,     25],
       [    30,     31,     32,     33,     34,     35],
       [100000,     41, 100000,     43, 100000,     45],
       [    50,     51,     52,     53,     54,     55]])

### Exercise (Post-Lecture)
Create the following matrix
```python
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
```

In [ ]:
# YOUR CODE HERE

Create the following matrix
```python
array([[-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1.,  0.,  1.,  2.,  3.,  4., -1., -1., -1., -1.],
       [-1.,  5.,  6.,  7.,  8.,  9., -1., -1., -1., -1.],
       [-1., 10., 11., 12., 13., 14., -1., -1., -1., -1.],
       [-1., 15., 16., 17., 18., 19., -1., -1., -1., -1.],
       [-1., 20., 21., 22., 23., 24., -1., -1., -1., -1.],
       [-1., 25., 26., 27., 28., 29., -1., -1., -1., -1.],
       [-1., 30., 31., 32., 33., 34., -1., -1., -1., -1.],
       [-1., 35., 36., 37., 38., 39., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.]])
```

In [ ]:
# YOUR CODE HERE

# Fancy Array Indexing

We can use numpy arrays as an index for other numpy arrays

In [78]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
# use array/list/tuple as indexs
idx = np.array([7,-1,2])
idx

array([ 7, -1,  2])

In [80]:
print(arr[idx])
arr[idx] = -1
arr

[7 9 2]


array([ 0,  1, -1,  3,  4,  5,  6, -1,  8, -1])

In [81]:
# use bool array
arr<0

array([False, False,  True, False, False, False, False,  True, False,
        True])

In [82]:
arr[arr<0] = 100
arr

array([  0,   1, 100,   3,   4,   5,   6, 100,   8, 100])

For multidimensional array, array indexing works different from slicing

In [83]:
X = np.zeros((6,6))
X[2:5,0:3]=1
X

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [84]:
np.arange(2,5), np.arange(0,3)

(array([2, 3, 4]), array([0, 1, 2]))

In [85]:
X = np.zeros((6,6))
X[np.arange(2,5),np.arange(0,3)]=1
X

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [86]:
# Here is our array, what should we return?
a = 10*np.arange(6).reshape(-1,1)+np.arange(6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [87]:
a[ (1,2,3,4,5), (0,1,2,3,4)]

array([10, 21, 32, 43, 54])

In [88]:
a[3:, [0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [90]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [93]:
mask = np.array([i for i in range(12) if i%2==0], dtype = bool)
print(mask)
a[mask,2]

[False  True  True  True  True  True]


array([12, 22, 32, 42, 52])

![](http://scipy-lectures.org/_images/numpy_fancy_indexing.png)

### Exercise (Post - Lecture)
Create the following matrix
```python
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])
```

In [ ]:
# YOUR CODE HERE

### Exercise (Post Lecture)
Write a function to compute the [trace](https://en.wikipedia.org/wiki/Trace_(linear_algebra)) of a square numpy array using fancy array indexing. Compare your implementation to numpy's built-in function `np.trace`.

In [ ]:
# YOUR CODE HERE

We can use `np.where`, to get indices of the `True` values in a boolean array

In [99]:
Y = np.arange(25).reshape(5,5)
print(Y)
Y[0,0] = 15
print(Y)
Y > 14
print(Y > 14)
print(np.where(Y>14))
Y[np.where(Y>14)]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[15  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ True False False False False]
 [False False False False False]
 [False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
(array([0, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4]), array([0, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))


array([15, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

## Reduction operations

Many reduction functions are available

- np.sum, np.prod
- np.min, np.max
- np.any, np.all

Partial reductions

- np.cumsum, np.cumprod

In [100]:
X = np.arange(50).reshape(10,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [101]:
np.sum(X),np.prod(X)

(1225, 0)

In [102]:
X.sum()

1225

The way to understand the “axis” of numpy sum is it collapses the specified axis. So when it collapses the axis 0 (row), it becomes just one row and column-wise sum.

In [106]:
np.sum(X, axis=1)

array([ 10,  35,  60,  85, 110, 135, 160, 185, 210, 235])

In [105]:
X.sum(axis = 1)

array([ 10,  35,  60,  85, 110, 135, 160, 185, 210, 235])

In [107]:
np.min(X),np.max(X)

(0, 49)

In [108]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [109]:
np.min(X,axis=1)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [119]:
S = np.zeros((5,2,3,4))
S.sum(axis=2)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [120]:
Y = X<12
Y

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [False, False, False, False]])

In [111]:
Y  + 10

array([[11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [112]:
np.any(Y, axis=1)

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [113]:
np.all(Y,axis=1)

array([ True,  True, False, False, False, False, False, False, False,
       False])

All the above functions can be called on the array object directly

In [114]:
# instance.method(args) = class.method(instance, args)
X.max(axis=0)

array([45, 46, 47, 48, 49])

In [115]:
# np.cumsum
Y = np.arange(10)
print(Y)
np.cumsum(Y)

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [116]:
X = np.arange(16).reshape(4,4)
print(X)
np.cumsum(X,axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38],
       [12, 25, 39, 54]])

Cumulative operations don't change the shape of the array

### Exercise (Post Lecture)

- Find the column with maximum column sum
- For which rows of the matrix, the sum of the first three elements of the row is greater than the sum of the last two elements of the row

In [ ]:
import numpy as np

In [ ]:
np.random.seed(10)
X = np.random.rand(5,5)
# YOUR CODE HERE

### Exercise (Post Lecture)
Compute the the moving average of the array `y` created below, with window size 5.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
np.random.seed(10)
y = np.cumsum(np.random.rand(100) - 0.5)
plt.plot(y)

In [ ]:
# YOUR CODE HERE

## Final Exercise (Post Lecture)

Implement the [Conway's game of Life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life) using numpy

In [ ]:
# YOUR CODE HERE